[package]
name = "bench-runner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.15"
regex = "1.5.4"
is_executable = "1.0.1"
ring = "0.16.20"
data-encoding = "2.3.2"