[package]
name = "bench-runner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
regex = "1.5.4"
is_executable = "1.0.1"
digest = "0.9.0"