[package]
edition.workspace = true
name = "repl_test"
version.workspace = true
authors.workspace = true
license.workspace = true
description = "Tests the roc REPL."

[build-dependencies]
roc_cli = {path = "../cli"}

[dev-dependencies]
indoc = "1.0.7"
strip-ansi-escapes = "0.1.1"
bumpalo.workspace = true

roc_build = { path = "../compiler/build" }
roc_repl_cli = {path = "../repl_cli"}
roc_test_utils = {path = "../test_utils"}
roc_wasm_interp = {path = "../wasm_interp"}

[features]
default = ["target-aarch64", "target-x86_64", "target-wasm32"]
wasm = ["target-wasm32"]
target-arm = ["roc_build/target-arm", "roc_repl_cli/target-arm"]
target-aarch64 = ["roc_build/target-aarch64", "roc_repl_cli/target-aarch64"]
target-x86 = ["roc_build/target-x86", "roc_repl_cli/target-x86"]
target-x86_64 = ["roc_build/target-x86_64", "roc_repl_cli/target-x86_64"]
target-wasm32 = ["roc_build/target-wasm32", "roc_repl_cli/target-wasm32"]

target-all = [
    "target-aarch64",
    "target-arm",
    "target-x86",
    "target-x86_64",
    "target-wasm32"
]
