[toolchain]
channel = "1.63.0" # make sure to update the rust version in Earthfile as well
profile = "default"
components = [
    # for usages of rust-analyzer or similar tools inside `nix develop`
    "rust-src"
]
targets = [ "x86_64-unknown-linux-gnu" ]
