[toolchain]
# How to update version:
#  - update `channel = "RUST_VERSION"`
#  - update `channel = "RUST_VERSION"` in examples/platform-switching/rust-platform/rust-toolchain.toml
#  - to update the nightly version:
#     - Find the latest nightly release that matches RUST_VERSION here: https://github.com/oxalica/rust-overlay/tree/master/manifests/nightly/2023
#     - update `channel = "nightly-OLD_DATE"` below
#     - update nightly-OLD_DATE in .github/workflows/windows_tests.yml
#     - update nightly-OLD_DATE in .github/workflows/windows_release_build.yml
#     - update nightly-OLD_DATE in crates/compiler/build/src/link.rs

channel = "1.67.1" # check ^^^ when changing this
# 
# channel = "nightly-2022-12-09" # 1.67.0 nightly to be able to use unstable features
profile = "default"
components = [
    # for usages of rust-analyzer or similar tools inside `nix develop`
    "rust-src"
]

targets = [
    "wasm32-wasi", # for test_wasm.sh
    "wasm32-unknown-unknown", # for repl_wasm
]
