[files]
extend-exclude = [
    ".git/",
    "design/language/Abilities.md",
    "src/snapshots/fuzz_crash",
    "crates/vendor/",
    "authors",
    "crates",
    "examples/static-site-gen/input/",
    "COPYRIGHT",
    "crates/compiler/checkmate/www/package-lock.json",
    "src/build/zig_llvm.h",
    "test/snapshots/",
    "build.zig.zon",
    "src/cli/darwin/",
    "src/backend/llvm/",
    "src/backend/dev/object/",
]

[default]
extend-ignore-identifiers-re = [".*_SME_.*"]

[default.extend-words]
typ = "typ"
ba = "ba"
sigfault = "sigfault"
nd = "nd"
olt = "olt"
