[files]
extend-exclude = [
    "design/language/Abilities.md",
    "src/snapshots/fuzz_crash",
    "crates/vendor/",
    "authors",
    "crates",
    "examples/static-site-gen/input/",
    "COPYRIGHT",
    "crates/compiler/checkmate/www/package-lock.json",
    "src/build/zig_llvm.h",
    "src/snapshots/",
]

[default]
extend-ignore-identifiers-re = [".*_SME_.*"]

[default.extend-words]
HSA = "HSA"
typ = "typ"
ba = "ba"
