[package]
name = "roc_types"
description = "Various representations and utilities for dealing with types in the Roc compiler."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_collections.workspace = true
roc_debug_flags.workspace = true
roc_error_macros.workspace = true
roc_module.workspace = true
roc_region.workspace = true
roc_serialize.workspace = true
roc_parse.workspace = true

ven_pretty.workspace = true

bumpalo.workspace = true
static_assertions.workspace = true

soa.workspace = true
bitflags.workspace = true
