[package]
name = "roc_types"
description = "Various representations and utilities for dealing with types in the Roc compiler."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../collections" }
roc_debug_flags = { path = "../debug_flags" }
roc_error_macros = { path = "../../error_macros" }
roc_module = { path = "../module" }
roc_region = { path = "../region" }
roc_serialize = { path = "../serialize" }
roc_parse = { path = "../parse" }

ven_pretty = { path = "../../vendor/pretty" }

bumpalo.workspace = true
static_assertions.workspace = true

soa.workspace = true
