[package]
name = "roc_parse"
version = "0.1.0"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2018"

[features]
# If enabled, parser accepts `Dict.#hashTestOnly` etc.
# For development puporpse.
keep_shadowed_builtins = []

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }
bumpalo = { version = "3.6.1", features = ["collections"] }
encode_unicode = "0.3"

[dev-dependencies]
pretty_assertions = "0.5.1"
indoc = "0.3.3"
quickcheck = "0.8"
quickcheck_macros = "0.8"
