[package]
name = "roc_highlight"
description = "For syntax highlighting, starts with a string and returns our markup nodes."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
html-escape = "0.2"
roc_parse = { path = "../compiler/parse" }
roc_region = { path = "../compiler/region" }

