[package]
name = "roc_mono"
description = "Roc's main intermediate representation (IR), which is responsible for monomorphization, defunctionalization, inserting ref-count instructions, and transforming a Roc program into a form that is easy to consume by a backend."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_builtins.workspace = true
roc_can.workspace = true
roc_collections.workspace = true
roc_debug_flags.workspace = true
roc_derive.workspace = true
roc_derive_key.workspace = true
roc_error_macros.workspace = true
roc_exhaustive.workspace = true
roc_late_solve.workspace = true
roc_module.workspace = true
roc_problem.workspace = true
roc_region.workspace = true
roc_std.workspace = true
roc_target.workspace = true
roc_tracing.workspace = true
roc_types.workspace = true
roc_solve_schema.workspace = true
roc_unify.workspace = true
ven_pretty.workspace = true

bitvec.workspace = true
arrayvec.workspace = true
bumpalo.workspace = true
hashbrown.workspace = true
parking_lot.workspace = true
static_assertions.workspace = true
indoc.workspace = true

rand = "0.8"
