[package]
name = "roc_module"
version = "0.1.0"
authors = ["Richard Feldman <oss@rtfeldman.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
roc_region = { path = "../region" }
roc_collections = { path = "../collections" }
bumpalo = { version = "3.2", features = ["collections"] }
inlinable_string = "0.1"
lazy_static = "1.4"

[dev-dependencies]
pretty_assertions = "0.5.1"
maplit = "1.0.1"
indoc = "0.3.3"
