[package]
name = "roc_load"
description = "Used to load a .roc file and coordinate the compiler pipeline, including parsing, type checking, and code generation."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_can.workspace = true
roc_can_solo.workspace = true
roc_collections.workspace = true
roc_load_internal.workspace = true
roc_module.workspace = true
roc_packaging.workspace = true
roc_reporting.workspace = true
roc_solve.workspace = true
roc_target.workspace = true
roc_types.workspace = true
bumpalo.workspace = true

[build-dependencies]
roc_builtins.workspace = true
roc_can.workspace = true
roc_module.workspace = true
roc_packaging.workspace = true
roc_reporting.workspace = true
roc_solve.workspace = true
roc_target.workspace = true
roc_error_macros.workspace = true
roc_load_internal.workspace = true
bumpalo.workspace = true

[dev-dependencies]
roc_constrain.workspace = true
roc_derive.workspace = true
roc_parse.workspace = true
roc_problem.workspace = true
roc_region.workspace = true
roc_solve_problem.workspace = true
ven_pretty.workspace = true
roc_test_utils_dir.workspace = true
indoc.workspace = true
insta.workspace = true
pretty_assertions.workspace = true
