[package]
authors = ["The Roc Contributors"]
edition = "2021"
license = "UPL-1.0"
name = "roc_unify"
version = "0.0.1"
description = "Implements Roc's unification algorithm, the heartstone of Roc's type inference."

[dependencies]
bitflags = "1.3.2"

[dependencies.roc_collections]
path = "../collections"

[dependencies.roc_error_macros]
path = "../../error_macros"

[dependencies.roc_module]
path = "../module"

[dependencies.roc_types]
path = "../types"

[dependencies.roc_debug_flags]
path = "../debug_flags"

[dependencies.roc_can]
path = "../can"

[dependencies.roc_solve_problem]
path = "../solve_problem"

[dependencies.roc_tracing]
path = "../../tracing"
