[package]
name = "cli_utils"
description = "Provides shared code for cli tests and benchmarks."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../compiler/collections" }
roc_load = { path = "../compiler/load" }
roc_module = { path = "../compiler/module" }
roc_reporting = { path = "../reporting" }
roc_command_utils = { path = "../utils/command" }
roc_error_macros = { path = "../error_macros" }

bumpalo.workspace = true
criterion.workspace = true
serde-xml-rs.workspace = true
serde.workspace = true
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
rlimit.workspace = true
