[package]
name = "roc_linker"
description = "A surgical linker for Roc"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "roc_linker"
path = "src/lib.rs"

[dependencies]
roc_collections = { path = "../compiler/collections" }
roc_error_macros = { path = "../error_macros" }
roc_module = { path = "../compiler/module" }
roc_load = { path = "../compiler/load" }
roc_mono = { path = "../compiler/mono" }
roc_packaging = { path = "../packaging" }
roc_reporting = { path = "../reporting" }
roc_solve = { path = "../compiler/solve" }
roc_target = { path = "../compiler/roc_target" }

bincode.workspace = true
bumpalo.workspace = true
iced-x86.workspace = true
mach_object.workspace = true
memmap2.workspace = true
object.workspace = true
serde.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true


[dev-dependencies]
indoc.workspace = true
libc.workspace = true
serial_test.workspace = true
