[package]
name = "roc_host"
version = "0.0.1"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2021"

links = "app"

[lib]
name = "roc_host"
path = "src/lib.rs"
crate-type = ["lib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
arrayvec = "0.7.2"
libc = "0.2"
page_size = "0.4.2"
roc_std = { path = "../../../crates/roc_std" }
cgmath = "0.18.0"
colored = "2.0.0"
copypasta = "0.7.1"
fs_extra = "1.2.0"
futures = "0.3.17"
glyph_brush = "0.7.2"
log = "0.4.14"
nonempty = "0.7.0"
palette = "0.6.0"
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1.0.130", features = ["derive"] }
snafu = { version = "0.6.10", features = ["backtraces"] }
threadpool = "1.8.1"
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "0545e36" }
wgpu_glyph = { git = "https://github.com/Anton-4/wgpu_glyph", rev = "257d109" }
winit = "0.26.1"

[features]
default = []

[dependencies.bytemuck]
features = ["derive"]
version = "1.7.2"

# Optimizations based on https://deterministic.space/high-performance-rust.html
[profile.release]
codegen-units = 1
lto = "thin"

# debug = true # enable when profiling
[profile.bench]
codegen-units = 1
lto = "thin"