[package]
name = "roc_repl_cli"
description = "Command Line Interface(CLI) functionality for the Read-Evaluate-Print-Loop (REPL)."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
# pipe target to roc_build
target-aarch64 = ["roc_build/target-aarch64"]
target-arm = ["roc_build/target-arm"]
target-x86 = ["roc_build/target-x86"]
target-x86_64 = ["roc_build/target-x86_64"]

[dependencies]
roc_build = { path = "../compiler/build" }
roc_builtins = { path = "../compiler/builtins" }
roc_bitcode = { path = "../compiler/builtins/bitcode" }
roc_collections = { path = "../compiler/collections" }
roc_gen_llvm = { path = "../compiler/gen_llvm" }
roc_gen_dev = { path = "../compiler/gen_dev" }
roc_load = { path = "../compiler/load" }
roc_mono = { path = "../compiler/mono" }
roc_parse = { path = "../compiler/parse" }
roc_region = { path = "../compiler/region" }
roc_repl_eval = { path = "../repl_eval" }
roc_reporting = { path = "../reporting" }
roc_std = { path = "../roc_std" }
roc_target = { path = "../compiler/roc_target" }
roc_types = { path = "../compiler/types" }
roc_error_macros = { path = "../error_macros" }
roc_repl_ui = { path = "../repl_ui" }

tempfile.workspace = true
bumpalo.workspace = true
const_format.workspace = true
inkwell.workspace = true
libloading.workspace = true
rustyline-derive.workspace = true
rustyline.workspace = true
target-lexicon.workspace = true

[lib]
name = "roc_repl_cli"
path = "src/lib.rs"
