[package]
name = "roc_load_internal"
description = "The internal implementation of roc_load, separate from roc_load to support caching."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_builtins.workspace = true
roc_can.workspace = true
roc_can_solo.workspace = true
roc_work.workspace = true
roc_checkmate.workspace = true
roc_collections.workspace = true
roc_constrain.workspace = true
roc_debug_flags.workspace = true
roc_derive.workspace = true
roc_derive_key.workspace = true
roc_error_macros.workspace = true
roc_late_solve.workspace = true
roc_module.workspace = true
roc_mono.workspace = true
roc_packaging.workspace = true
roc_parse.workspace = true
roc_problem.workspace = true
roc_region.workspace = true
roc_reporting.workspace = true
roc_solve.workspace = true
roc_solve_problem.workspace = true
roc_target.workspace = true
roc_tracing.workspace = true
roc_types.workspace = true
roc_unify.workspace = true
roc_worker.workspace = true
roc_lower_params.workspace = true
ven_pretty.workspace = true
bumpalo.workspace = true
crossbeam.workspace = true
parking_lot.workspace = true
tempfile.workspace = true
base64-url.workspace = true
blake3.workspace = true

[dev-dependencies]
roc_test_utils_dir.workspace = true
indoc.workspace = true
maplit.workspace = true
pretty_assertions.workspace = true
