[package]
name = "roc_docs"
description = "Generates html documentation from Roc files and is used for Rocs builtins."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_ast = { path = "../ast" }
roc_builtins = { path = "../compiler/builtins" }
roc_can = { path = "../compiler/can" }
roc_code_markup = { path = "../code_markup" }
roc_collections = { path = "../compiler/collections" }
roc_highlight = { path = "../highlight" }
roc_load = { path = "../compiler/load" }
roc_module = { path = "../compiler/module" }
roc_packaging = { path = "../packaging" }
roc_parse = { path = "../compiler/parse" }
roc_region = { path = "../compiler/region" }
roc_reporting = { path = "../reporting" }
roc_solve = { path = "../compiler/solve" }
roc_target = { path = "../compiler/roc_target" }
roc_types = { path = "../compiler/types" }

bumpalo.workspace = true
peg.workspace = true
pulldown-cmark.workspace = true
snafu.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
