[package]
name = "roc_docs"
version = "0.0.1"
license = "UPL-1.0"
authors = ["The Roc Contributors"]
edition = "2021"
description = "Generates html documentation from Roc files and is used for Rocs builtins."

[dependencies]
pulldown-cmark = { version = "0.9.2", default-features = false }
roc_ast = { path = "../ast" }
roc_load = { path = "../compiler/load" }
roc_builtins = { path = "../compiler/builtins" }
roc_can = { path = "../compiler/can" }
roc_code_markup = { path = "../code_markup"}
roc_module = { path = "../compiler/module" }
roc_region = { path = "../compiler/region" }
roc_types = { path = "../compiler/types" }
roc_parse = { path = "../compiler/parse" }
roc_target = { path = "../compiler/roc_target" }
roc_collections = { path = "../compiler/collections" }
roc_highlight = { path = "../highlight"}
roc_packaging = { path = "../packaging"}
roc_reporting = { path = "../reporting"}
bumpalo.workspace = true
snafu.workspace  = true
peg.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
