[package]
name = "test_mono"
version = "0.1.0"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2018"

[dev-dependencies]
roc_collections = { path = "../collections" }
roc_module = { path = "../module" }
roc_builtins = { path = "../builtins" }
roc_load = { path = "../load" }
roc_can = { path = "../can" }
roc_mono = { path = "../mono" }
test_mono_macros = { path = "../test_mono_macros" }
pretty_assertions = "0.5.1"
bumpalo = { version = "3.6.1", features = ["collections"] }
indoc = "0.3.3"
