[package]
name = "roc_builtins"
description = "Provides the Roc functions and modules that are implicitly imported into every module."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../collections" }
roc_module = { path = "../module" }
roc_region = { path = "../region" }
roc_target = { path = "../roc_target" }

tempfile.workspace = true

