[package]
name = "roc_target"
description = "Provides types and helpers for compiler targets such as default_x86_64."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_error_macros.workspace = true

strum.workspace = true
strum_macros.workspace = true
target-lexicon.workspace = true
