[package]
name = "roc_builtins_bitcode"
version = "0.1.0"
authors = ["Richard Feldman <richard.t.feldman@gmail.com>"]
repository = "https://github.com/rtfeldman/roc"
readme = "README.md"
edition = "2018"
description = "Generate LLVM bitcode for Roc builtins"
license = "Apache-2.0"


[build]
target-dir="~/code/roc/copmiler/builtins/bitcode/"
