[package]
edition = "2021"
name = "repl_test"
version = "0.1.0"

[[test]]
name = "repl_test"
path = "src/tests.rs"

[dev-dependencies]
indoc = "1.0.3"
roc_test_utils = {path = "../test_utils"}
strip-ansi-escapes = "0.1.1"

roc_repl_cli = {path = "../repl_cli"}
# roc_repl_wasm = {path = "../repl_wasm"}

[features]
default = ["cli"]
cli = []
wasm = []
