[package]
authors = ["The Roc Contributors"]
description = "Rust representations of Roc data structures"
edition = "2021"
license = "UPL-1.0"
name = "roc_std"
readme = "README.md"
repository = "https://github.com/rtfeldman/roc"
version = "0.0.1"

[dependencies]
static_assertions = "1.1.0"
arrayvec = "0.7.2"
serde = { version = "1", optional = true }

[dev-dependencies]
indoc = "1.0.3"
pretty_assertions = "1.0.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
libc = "0.2.106"

[features]
std = []
serde = ["dep:serde"]
