[package]
name = "test_syntax"
description = "Tests for the parse + fmt crates."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
"parse_debug_trace" = ["roc_parse/parse_debug_trace"]

[dependencies]
bumpalo.workspace = true
roc_can.workspace = true
roc_can_solo.workspace = true
roc_collections.workspace = true
roc_error_macros.workspace = true
roc_fmt.workspace = true
roc_module.workspace = true
roc_parse.workspace = true
roc_region.workspace = true
roc_test_utils.workspace = true
roc_test_utils_dir.workspace = true
roc_types.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
walkdir.workspace = true
