on:
  pull_request:
    paths-ignore:
          - '**.md'

name: Benchmarks

env:
  RUST_BACKTRACE: 1

jobs:
  prep-dependency-container:
    name: benchmark roc programs
    runs-on: [self-hosted, i7-6700K]
    timeout-minutes: 60
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "trunk"
          clean: "true" 

      - name: Earthly version
        run: earthly --version

      - name: on trunk; prepare a self-contained benchmark folder
        run: ./ci/safe-earthly.sh --build-arg BENCH_SUFFIX=trunk +prep-bench-folder 

      - uses: actions/checkout@v2
        with:
          clean: "false" # we want to keep the benchmark folder

      - name: on current branch; prepare a self-contained benchmark folder
        run: ./ci/safe-earthly.sh +prep-bench-folder

      - name: execute benchmarks with regression check
        run: ./ci/bench-runner.sh
