name: CI Manager

on:
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    outputs:
      zig: ${{ steps.filter.outputs.zig }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            zig:
              - 'src/**'
              - 'build.zig'
              - 'build.zig.zon'
            other_than_zig:
              - '**/*'
              - '!src/**'
              - '!build.zig'
              - '!build.zig.zon'

  call-zig-workflow:
    needs: check-changes
    if: needs.changes.outputs.zig == 'true'
    uses: ./.github/workflows/ci_zig.yml

  call-old-workflow:
    needs: check-changes
    if: needs.changes.outputs.other_than_zig == 'true'
    uses: ./.github/workflows/ci_manager_old.yml
    
  finish:
    needs: [check-changes, call-zig-workflow, call-old-workflow]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check workflow results
        run: |
          if [[ "${{ needs.changes.outputs.zig }}" == "true" ]]; then
            if [[ "${{ needs.call-zig-workflow.result }}" != "success" ]]; then
              echo "ci_zig.yml failed."
              exit 1
            fi
          else
            if [[ "${{ needs.call-old-workflow.result }}" != "success" ]]; then
              echo "ci_manager_old.yml failed."
              exit 1
            fi
          fi