on:
    pull_request:
  
name: Test the devtools nix files

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    devtools-test:
        name: devtools-test
        runs-on: [ubuntu-20.04]
        timeout-minutes: 120
        steps:
            - uses: actions/checkout@v3

            - name: Only run all steps if flake.lock changed
              run: |
                if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'flake.lock'; then
                  echo "Flake.lock was changed. Testing devtools nix files..."
                else
                  echo "Flake.lock was not changed. No need to run tests. Exiting..."
                  exit 0
                fi

            - uses: cachix/install-nix-action@v23
              with:
                nix_path: nixpkgs=channel:nixos-unstable

            - name: update roc folder path
              run: |
                sed -i "s|/home/anton/gitrepos/roc|$(realpath .)|g" devtools/flake.nix
                cat devtools/flake.nix

            - name: test devtools/flake.nix
              id: devtools_test_step
              run: |
                mkdir -p ../temp
                cp devtools/flake.nix ../temp
                cp devtools/flake.lock ../temp
                cd ../temp
                git init
                git add flake.nix flake.lock
                nix develop

            - name: Print tip on fail
              if: steps.devtools_test_step.outcome == 'failure'
              run: |
                echo "The devtools test failed, this can likely be fixed by"
                echo "locally deleting devtools/flake.lock and following the"
                echo "instructions in devtools/README.md. This will create a"
                echo "new flake.lock you should use to replace the old devtools/flake.lock"


  
