on:
  pull_request:

name: Macos x86-64 rust tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test-rust-macos-x86-64:
    runs-on: [self-hosted, macOS, X64]
    timeout-minutes: 90
    env:
      RUSTC_WRAPPER: /Users/username1/.cargo/bin/sccache
    steps:
      - uses: actions/checkout@v3

      - name: set LLVM_SYS_160_PREFIX
        run: echo "LLVM_SYS_160_PREFIX=$(brew --prefix llvm@16)" >> $GITHUB_ENV

      - run: echo $LLVM_SYS_160_PREFIX

      - run: ls $LLVM_SYS_160_PREFIX

      - name: Update PATH to use zig 11
        run: |
          echo "PATH=/Users/username1/Downloads/zig-macos-x86_64-0.11.0:$PATH" >> $GITHUB_ENV
    
      - run: zig version

      - name: test_gen llvm tests
        run: cargo nextest-gen-llvm --release --no-fail-fast --locked -E "package(test_gen) - test(gen_str::str_append_scalar)"

      - name: regular rust tests
        run: cargo test --locked --release -- --skip opaque_wrap_function --skip gen_list::bool_list_literal --skip platform_switching_swift --skip swift_ui --skip gen_str::str_append_scalar --skip gen_tags::phantom_polymorphic_record && sccache --show-stats
        # swift tests are skipped because of "Could not find or use auto-linked library 'swiftCompatibilityConcurrency'" on macos-11 x86_64 CI machine
        # this issue may be caused by using older versions of XCode
