on:
  pull_request:

name: Macos x86-64 rust tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test-rust-macos-x86-64:
    runs-on: [self-hosted, macOS, X64]
    timeout-minutes: 90
    env:
      RUSTC_WRAPPER: /Users/username1/.cargo/bin/sccache
    steps:
      - uses: actions/checkout@v2
        with:
          clean: "true"

      - name: regular rust tests
        run: cargo test --locked --release -- --skip opaque_wrap_function --skip gen_list::bool_list_literal --skip platform_switching_swift --skip swift_ui --skip gen_str::str_append_scalar --skip gen_tags::phantom_polymorphic_record && sccache --show-stats
        # swift tests are skipped because of "Could not find or use auto-linked library 'swiftCompatibilityConcurrency'" on macos-11 x86_64 CI machine
        # this issue may be caused by using older versions of XCode

      - name: test launching the editor
        run: cargo test --release --locked editor_launch_test::launch -- --ignored # `--ignored` to run this test that is ignored for "normal" runs
