on:
  workflow_call:

name: Macos x86-64 rust tests

env:
  RUST_BACKTRACE: 1

jobs:
  test-rust-macos-x86-64:
    runs-on: [self-hosted, macOS, X64]
    timeout-minutes: 90
    env:
      RUSTC_WRAPPER: /Users/username1/.cargo/bin/sccache
    steps:
      - uses: actions/checkout@v4

      - name: set LLVM_SYS_180_PREFIX
        run: echo "LLVM_SYS_180_PREFIX=$(brew --prefix llvm@18)" >> $GITHUB_ENV

      - name: check for zig 13
        run: ls /Users/username1/Downloads/zig-macos-x86_64-0.13.0

      - name: Update PATH to use zig 13
        run: |
          echo "PATH=/Users/username1/Downloads/zig-macos-x86_64-0.13.0:$PATH" >> $GITHUB_ENV

      - run: zig version

      - name: test_gen llvm tests
        run: cargo nextest-gen-llvm --release --no-fail-fast --locked -E "package(test_gen) - test(gen_str::str_append_scalar)"

      - name: regular rust tests
        run: cargo test --locked --release -- --skip opaque_wrap_function --skip gen_list::bool_list_literal --skip gen_tags::phantom_polymorphic_record && sccache --show-stats
