on:
  schedule:
    - cron:  '0 0 * * *'

name: Nightly Release Build

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1 # for earthly logging
    steps:
      - uses: actions/checkout@v2
      - name: install earthly
        run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
      - name: Earthly print version
        run: earthly --version
      - name: install dependencies, build, run tests, build release
        run: ./ci/safe-earthly.sh +build-nightly-release
      - name: Create pre-release with test_archive.tar.gz
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/rtfeldman/roc/releases/51880579/assets{?name,label}
          release_id: 51880579
          asset_path: ./roc_linux_x86_64.tar.gz
          asset_name: roc_nightly-linux_x86_64-$$.tar.gz # $$ to inserts date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/gzip
          max_releases: 3

