on:
  #pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

name: Nightly Release Old Linux x86_64 using Earthly

jobs:
  build:
    name: build and package nightly release
    runs-on: [ubuntu-22.04]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - name: get commit SHA
        run:  echo "SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: get date
        run: echo "DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

      - name: build file name
        env:
            DATE: ${{ env.DATE }}
            SHA: ${{ env.SHA }}
        run: echo "RELEASE_FOLDER_NAME=roc_nightly-old_linux_x86_64-$DATE-$SHA" >> $GITHUB_ENV

      - name: install earthly
        run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

      - run: earthly --version

      - name: build release with earthly
        run: earthly +build-nightly-release  --RELEASE_FOLDER_NAME=${{ env.RELEASE_FOLDER_NAME }} --RUSTFLAGS="-C target-cpu=x86-64"

      - name: Upload roc nightly tar. Actually uploading to github releases has to be done manually.
        uses: actions/upload-artifact@v4
        with:
           name: ${{ env.RELEASE_FOLDER_NAME }}.tar.gz
           path: ${{ env.RELEASE_FOLDER_NAME }}.tar.gz
           retention-days: 4
