on:
  #pull_request:

name: Nix macOS x86_64 cargo test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  nix-macos-x86-64:
    name: nix-macos-x86-64
    runs-on: [macos-12]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22

      - name: execute cli_run tests only, the full tests take too long but are run nightly
        run: nix develop -c cargo test --locked --release -p roc_cli

      - name: make a libapp.so for the next step
        run: nix develop -c cargo run -- gen-stub-lib examples/platform-switching/rocLovesRust.roc

      - name: check that the platform`s produced dylib is loadable
        run: cd examples/platform-switching/rust-platform && nix develop -c cargo test --release --locked
