on:
  workflow_call:

name: Nix apple silicon cargo test

# Do not add permissions here! Configure them at the job level!
permissions: {}

env:
  RUST_BACKTRACE: 1

jobs:
  nix-apple-silicon:
    name: nix-apple-silicon
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      # These started to accumulate quickly since #5990, not sure why
      - name: Clean up old nix shells
        run: rm -rf /private/tmp/nix-shell.*
        
      - name: check formatting with rustfmt
        run: nix develop -c cargo fmt --all -- --check

      - name: check code style with clippy
        run: nix develop -c cargo clippy --workspace --tests -- --deny warnings -v

      - name: check code style with clippy --release
        run: nix develop -c cargo clippy --workspace --tests --release -- --deny warnings -v

      - name: test building default.nix
        run: nix-build

      # for skipped tests: see issue 6274
      - name: execute tests with --release
        run: nix develop -c cargo test --locked --release -- --skip cli_tests::inspect_gui --skip cli_tests::hello_gui

      - name: roc test all builtins
        run: nix develop -c ./ci/roc_test_builtins.sh

      - name: test aarch64 dev backend
        run: nix develop -c cargo nextest-gen-dev --locked --release --no-fail-fast -v

      # we run the llvm wasm tests only on this machine because it is fast and wasm should be cross-target
      - name: execute llvm wasm tests with --release
        run: nix develop -c cargo test-gen-llvm-wasm --locked --release

      - name: set env var and test website build script
        run: |
          nix develop -c bash www/build.sh

      - name: wasm repl tests
        run: nix develop -c crates/repl_test/test_wasm.sh

      - name: test building wasm repl
        run: nix develop -c ./ci/www-repl.sh
