on: [pull_request]

name: SpellCheck

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  spell-check:
    name: spell check
    runs-on: [self-hosted, i7-6700K]
    timeout-minutes: 10
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          clean: "true"

      - name: Earthly version
        run: earthly --version

      - name: install spell checker, do spell check
        run: ./ci/safe-earthly.sh +check-typos
