on:
#  pull_request:
  workflow_dispatch:

name: Test latest nightly releases for macOS and Linux

# Do not add permissions here! Configure them at the job level!
permissions: {}

jobs:
  test-nightly:
    name: test nightly macos 15 intel (x64), macos 14 (aarch64), ubuntu 22.04-24.04 (x64), ubuntu 22.04-24.04 (aarch64)
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-14, ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f # 2.0.5
        with:
          version: 0.13.0

      - name: Delete everything except ci folder to test the release like a real user would
        run: find . -maxdepth 1 ! -name ci ! -name '.' -exec rm -rf {} +

      - name: get the latest release archive for linux (x86_64)
        if: startsWith(matrix.os, 'ubuntu') && !endsWith(matrix.os, '-arm')
        run: |
          curl -fL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz -o roc_release.tar.gz

      - name: get the latest release archive for linux (arm64)
        if: startsWith(matrix.os, 'ubuntu') && endsWith(matrix.os, '-arm')
        run: |
          curl -fL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_arm64-latest.tar.gz -o roc_release.tar.gz

      - name: get the latest release archive for macos 15 intel (x86_64)
        if: matrix.os == 'macos-15-intel'
        run: curl -fL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_x86_64-latest.tar.gz -o roc_release.tar.gz

      - name: get the latest release archive for macos 14 (aarch64)
        if: matrix.os == 'macos-14'
        run: curl -fL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_apple_silicon-latest.tar.gz -o roc_release.tar.gz

      - run: zig version

      - name: prep and run basic tests
        run: |
          ./ci/basic_release_test.sh roc_release.tar.gz