on:
  schedule:
    - cron:  '0 13 * * *'

name: Test latest nightly release for macOS x86_64

jobs:
  test-nightly:
    name: test nightly macos x86_64
    strategy:
      matrix:
        os: [ macos-12, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - name: fetch releases data and save to file
        run: |
          curl --request GET \
          --url https://api.github.com/repos/roc-lang/roc/releases \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --output roc_releases.json

      - name: get the url of today`s release for linux x86_64
        if: startsWith(matrix.os, 'ubuntu')
        run: echo "RELEASE_URL=$(./ci/get_latest_release_url.sh linux_x86_64)" >> $GITHUB_ENV

      - name: get the url of today`s release for macos x86_64
        if: startsWith(matrix.os, 'macos')
        run: echo "RELEASE_URL=$(./ci/get_latest_release_url.sh macos_x86_64)" >> $GITHUB_ENV

      - name: get the archive from the url
        run: curl -OL ${{ env.RELEASE_URL }}

      - name: remove everything in this dir except the tar # we want to test like a user who would have downloaded the release, so we clean up all files from the repo checkout
        run: ls | grep -v "roc_nightly.*tar\.gz" | xargs rm -rf

      - name: decompress the tar
        run: ls | grep "roc_nightly.*tar\.gz" | xargs tar -xzvf

      - name: test roc hello world
        run: ./roc examples/hello-world/main.roc



